apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
    - port: 3050       # Service port
      targetPort: 3050  # Container port (Tomcat)
      protocol: TCP
      nodePort: 31000
